//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalRxNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PracticalRxNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;#4c4f56&quot;: &quot;Abbey&quot;,
        ///  &quot;#0048ba&quot;: &quot;Absolute Zero&quot;,
        ///  &quot;#1b1404&quot;: &quot;Acadia&quot;,
        ///  &quot;#7cb0a1&quot;: &quot;Acapulco&quot;,
        ///  &quot;#b0bf1a&quot;: &quot;Acid Green&quot;,
        ///  &quot;#7cb9e8&quot;: &quot;Aero&quot;,
        ///  &quot;#c9ffe5&quot;: &quot;Aero Blue&quot;,
        ///  &quot;#714693&quot;: &quot;Affair&quot;,
        ///  &quot;#b284be&quot;: &quot;African Violet&quot;,
        ///  &quot;#00308f&quot;: &quot;Air Force Blue&quot;,
        ///  &quot;#72a0c1&quot;: &quot;Air Superiority Blue&quot;,
        ///  &quot;#d4c4a8&quot;: &quot;Akaroa&quot;,
        ///  &quot;#af002a&quot;: &quot;Alabama Crimson&quot;,
        ///  &quot;#fafafa&quot;: &quot;Alabaster&quot;,
        ///  &quot;#f5e9d3&quot;: &quot;Albescent White&quot;,
        ///  &quot;#93dfb8&quot;: &quot;Algae Green&quot;,
        ///  &quot;#f0f8ff&quot;: &quot;Alice Blue&quot;,
        ///  &quot;#84de02&quot;: &quot;Alien Armpit&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ColorsJson {
            get {
                return ResourceManager.GetString("ColorsJson", resourceCulture);
            }
        }
    }
}
